# Generated by Django 5.0.6 on 2024-05-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
